Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,10 +22,20 @@ jobs:
       - name: Deploy and run Docker on VPS
         run: |
           ssh -i ~/.ssh/id_rsa root@160.250.134.253 << 'EOF'
+            set -e
+
             cd /home/cnpm/CNPM-BE || exit 1
 
             echo "Pull latest code"
             git pull origin main
+
+            # Kiểm tra file ENV có tồn tại không, nếu không thì tạo từ secret
+            if [ ! -f ENV ]; then
+              echo "ENV file not found, creating from secret"
+              cat > ENV << 'EOL'
+							${{ secrets.ENV}}
+						EOL
+            fi
 
             echo "Build Docker image"
             docker build -t my-nest-backend .
